name: VUE

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Run Test
        # Install a project with a clean slate (required package-lock.json)
        # npm ci will: Delete the node_modules folder
        # npm ci will: Install all package-lock.json dependencies.
        run: |
          npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vue-cicd:1.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}