
name: CI

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

    workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-lastet
      steps:
        -  uses: actions/checkout@v2
        -  name: Run a one-line script
        -  run: echo Hello,world!
          
          
